- name: Create local initial kubeconfig
  ansible.builtin.command: >
    kubectl config set-cluster kubernetes-the-hard-way
    --certificate-authority="{{ certs_path }}/ca.crt"
    --embed-certs=true
    --server=https://server.kubernetes.local:6443
    --kubeconfig="{{ kubeconfigs_path }}/local.kubeconfig"
  args:
    creates: "{{ kubeconfigs_path }}/local.kubeconfig"
  register: initiallocalkubeconfig

- name: Set credentials for local kubeconfig
  ansible.builtin.command: >
    kubectl config set-credentials admin
    --client-certificate="{{ certs_path }}/admin.crt"
    --client-key="{{ certs_path }}/admin.key"
    --embed-certs=true
    --kubeconfig="{{ kubeconfigs_path }}/local.kubeconfig"
  when: initiallocalkubeconfig.changed

- name: Set context for local kubeconfig
  ansible.builtin.command: >
    kubectl config set-context kubernetes-the-hard-way
    --cluster=kubernetes-the-hard-way
    --user=admin
    --kubeconfig="{{ kubeconfigs_path }}/local.kubeconfig"
  when: initiallocalkubeconfig.changed

- name: Use context for local kubeconfig
  ansible.builtin.command: >
    kubectl config use-context kubernetes-the-hard-way
    --kubeconfig="{{ kubeconfigs_path }}/local.kubeconfig"
  when: initiallocalkubeconfig.changed