---
- name: Create encryption folder
  ansible.builtin.file:
    path: "{{ encryption_config_path }}"
    state: directory
    mode: 0700

- name: Generate random base64 encoded random string with length 32
  ansible.builtin.set_fact:
    encryption_key: "{{ lookup('community.general.random_string', length=32, base64=True) }}"

- name: Create the encryption config file
  ansible.builtin.template:
    src: encryption-config.j2
    dest: "{{ encryption_config_path }}/encryption-config.yaml"