---
- name: Create kubelet directory
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - /var/lib/kube-proxy
    - /var/lib/kubelet

- name: Copy kubelet kubeconfig
  become: true
  ansible.builtin.copy:
    src: "{{ kubeconfigs_path }}/{{ inventory_hostname }}.kubeconfig"
    dest: /var/lib/kubelet/kubeconfig
    mode: 0644

- name: Copy kube-proxy kubeconfig
  become: true
  ansible.builtin.copy:
    src: "{{ kubeconfigs_path }}/kube-proxy.kubeconfig"
    dest: /var/lib/kube-proxy/kubeconfig
    mode: 0644
