---
- name: Copy Kubernetes kubeconfigs
  become: true
  ansible.builtin.copy:
    src: "{{ kubeconfigs_path }}/{{ item }}.kubeconfig"
    dest: "/home/admin/{{ item }}.kubeconfig"
    mode: 0644
  loop:
    - admin
    - kube-controller-manager
    - kube-scheduler
